"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, BookOpen, BriefcaseBusiness, Check, ChevronLeft, Clock3, ExternalLink, Headphones, History, Home, LoaderCircle, Pause, Play, Plus, Settings, Sparkles, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { BriefView, ProfileUpdate } from "@/lib/domain";

const PRESETS = ["טכנולוגיה", "AI", "קריפטו", "ריבית ואינפלציה", "כלכלת ישראל", "כלכלה עולמית", "שוק הנדל״ן", "אנרגיה", "מט״ח", "אג״ח", "ביוטק ופארמה", "שבבים"];
type Profile = ProfileUpdate;
const EMPTY: Profile = { targetMinutes: 7, onboardingComplete: false, assets: [], interests: [] };

function Brand() { return <Link href="/today" className="brand"><span className="brand-mark">sli<i>n</i>on</span><b>חסכהון</b></Link>; }
function fmt(ms?: number | null) { const sec = Math.round((ms || 0) / 1000); return Math.floor(sec / 60) + ":" + String(sec % 60).padStart(2, "0"); }
function Notice({ children }: { children: React.ReactNode }) { return <div className="notice" role="alert">{children}</div>; }
function Loading() { return <div className="center-screen"><div className="orb"><LoaderCircle className="spin"/></div><p>טוענים את חסכהון…</p></div>; }

function Shell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const nav = [{ href: "/today", label: "היום", icon: Home }, { href: "/portfolio", label: "תיק", icon: BriefcaseBusiness }, { href: "/preferences", label: "העדפות", icon: Settings }];
  return <div className="app-shell"><header className="topbar"><Brand/><nav>{nav.map(({href,label,icon:Icon}) => <Link key={href} className={pathname.startsWith(href) ? "active" : ""} href={href}><Icon/>{label}</Link>)}</nav></header><main className="workspace">{children}</main><nav className="bottom-nav">{nav.map(({href,label,icon:Icon}) => <Link key={href} className={pathname.startsWith(href) ? "active" : ""} href={href}><Icon/><span>{label}</span></Link>)}</nav></div>;
}

export function HaskahonApp() {
  const pathname = usePathname(); const router = useRouter();
  const [profile, setProfile] = useState<Profile>(EMPTY); const [briefs, setBriefs] = useState<BriefView[]>([]); const [draftText, setDraftText] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let ignore=false; Promise.all([fetch("/api/profile").then(r=>r.json() as Promise<Profile>),fetch("/api/briefs").then(r=>r.json() as Promise<BriefView[]>),fetch("/api/onboarding/draft").then(r=>r.json() as Promise<{text:string;assets:Profile["assets"]}>)]).then(([p,b,d])=>{if(!ignore){setProfile(!p.onboardingComplete&&d.assets.length?{...p,assets:[...p.assets.filter(a=>a.kind!=="holding"),...d.assets]}:p);setBriefs(b);setDraftText(d.text)}}).catch(()=>{if(!ignore)setError("לא הצלחנו לקרוא את הנתונים המקומיים.")}).finally(()=>{if(!ignore)setLoading(false)}); return()=>{ignore=true}; }, []);
  if (loading) return <Loading/>;
  if (pathname === "/") return <Landing onStart={() => router.push(profile.onboardingComplete ? "/today" : "/onboarding/portfolio")}/>;
  if (pathname.startsWith("/onboarding")) return <Onboarding profile={profile} setProfile={setProfile} text={draftText} setText={setDraftText}/>;
  if (pathname.startsWith("/generate/")) return <Generating id={pathname.split("/").pop() || ""}/>;
  return <Shell>{error && <Notice>{error}</Notice>}{pathname === "/portfolio" ? <Portfolio profile={profile} setProfile={setProfile}/> : pathname === "/preferences" ? <Preferences profile={profile} setProfile={setProfile}/> : pathname === "/archive" ? <ArchivePage briefs={briefs}/> : pathname.startsWith("/briefs/") ? <Player id={pathname.split("/").pop() || ""}/> : <Today profile={profile} briefs={briefs}/>}</Shell>;
}

function Landing({ onStart }: { onStart: () => void }) {
  return <main className="landing"><div className="ambient a"/><div className="ambient b"/><section><div className="hero-brand"><span className="brand-mark large">sli<i>n</i>on</span><h1>חסכהון</h1></div><p className="eyebrow">הבריף הפיננסי שנבנה סביבך</p><h2>כל מה שחשוב להשקעות שלך,<br/><em>בכמה דקות של הקשבה.</em></h2><p className="lead">חדשות השוק שנוגעות לתיק ולתחומי העניין שלך, מסודרות לבריף קולי ברור בעברית.</p><Button size="lg" onClick={onStart} className="primary-cta">יצירת הבריף הראשון שלי <ArrowLeft/></Button><Card className="demo-brief"><button aria-label="ניגון הדגמה"><Play fill="currentColor"/></button><div><b>הבריף של היום</b><span>מותאם אישית</span></div><Wave/><small>6:24</small></Card><div className="benefits"><span><Sparkles/>מותאם אליך</span><span><Clock3/>חוסך זמן</span><span><BookOpen/>מבוסס מקורות</span></div></section></main>;
}

function Wave() { return <div className="wave" dir="ltr" aria-hidden="true">{Array.from({length:38},(_,i)=><i key={i} style={{height: 10 + (i * 17) % 34}}/>)}</div>; }

function Onboarding({profile,setProfile,text,setText}:{profile:Profile;setProfile:(p:Profile)=>void;text:string;setText:(text:string)=>void}) {
  const pathname=usePathname(); const router=useRouter(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [custom,setCustom]=useState(""); const [watch,setWatch]=useState("");
  const holdings=profile.assets.filter(a=>a.kind==="holding");
  async function parse(){setBusy(true);setMessage("");try{const r=await fetch("/api/portfolio/parse",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});const data=await r.json() as {assets:Profile["assets"];error?:string};if(!r.ok)throw new Error(data.error);if(!data.assets.length)throw new Error("לא זוהה נכס בטקסט. נסו לכתוב שם חברה או סימול.");const parsedHoldings=data.assets.map((a:Profile["assets"][number])=>({...a,kind:"holding" as const}));const draft=await fetch("/api/onboarding/draft",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,assets:parsedHoldings})});if(!draft.ok)throw new Error("שמירת הטיוטה המקומית נכשלה.");const next={...profile,assets:[...profile.assets.filter(a=>a.kind!=="holding"),...parsedHoldings]};setProfile(next);router.push("/onboarding/confirm");}catch(e){setMessage(e instanceof Error?e.message:"לא הצלחנו לזהות את הנכסים.");}finally{setBusy(false)}}
  async function finish(){setBusy(true);const final={...profile,onboardingComplete:true};const save=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(final)});if(!save.ok){setMessage("שמירת הפרופיל נכשלה.");setBusy(false);return;}await fetch("/api/onboarding/draft",{method:"DELETE"});setProfile(final);const r=await fetch("/api/briefs",{method:"POST"});const data=await r.json() as {id:string};if(r.ok)router.push("/generate/"+data.id);else{setMessage("לא הצלחנו להתחיל ביצירת הבריף.");setBusy(false)}}
  const interests=profile.interests.map(i=>i.label);
  const step=pathname.endsWith("interests")?2:1;
  return <main className="onboarding"><div className="ambient a"/><Card className="onboarding-card"><Brand/><div className="step"><span>שלב {step} מתוך 3</span><Progress value={step===1?33:66}/></div>
    {pathname.endsWith("portfolio") ? <><h1>מה יש בתיק ההשקעות שלך?</h1><p>פשוט כתבו את הנכסים שאתם מחזיקים. רק שם הנכס נדרש — פרטים נוספים אפשר להוסיף אחר כך.</p><label htmlFor="portfolio-text">כתבו את תיק ההשקעות שלכם</label><Textarea id="portfolio-text" value={text} onChange={e=>setText(e.target.value)} placeholder="לדוגמה: NVIDIA, S&P 500 ו־Bitcoin" rows={5}/><small>חסכהון יציג את מה שהבין לפני השמירה ולעולם לא ימציא כמויות או שווי.</small>{message&&<Notice>{message}</Notice>}<Button disabled={!text.trim()||busy} onClick={parse} className="primary-cta">{busy?<LoaderCircle className="spin"/>:<ArrowLeft/>} המשך</Button></>:
    pathname.endsWith("confirm") ? <><h1>זה מה שהבנו מהתיק שלך</h1><p>בדקו שהנכסים זוהו נכון לפני שממשיכים.</p><div className="asset-listDashboard">{holdings.map((a,i)=><Card key={a.symbol+i} className="asset-row"><span className="ticker">{a.symbol.slice(0,2)}</span><div><b>{a.name}</b><small>{a.symbol}</small></div><Button variant="ghost" size="icon" aria-label={"הסרת "+a.name} onClick={()=>setProfile({...profile,assets:profile.assets.filter(x=>x!==a)})}><Trash2/></Button></Card>)}</div><Button disabled={!holdings.length} onClick={()=>router.push("/onboarding/interests")} className="primary-cta">אישור והמשך <ArrowLeft/></Button><Button variant="ghost" onClick={()=>router.push("/onboarding/portfolio")}>חזרה לעריכה</Button></>:
    <><h1>על מה עוד תרצו שחסכהון יעקוב?</h1><p>הוסיפו נכסים ונושאים שמעניינים אתכם — גם אם הם לא נמצאים בתיק.</p><div className="section-card"><div className="section-title"><h3>נכסים במעקב</h3><span>אופציונלי</span></div><p>חברות או נכסים שתרצו להתעדכן לגביהם גם בלי להחזיק בהם.</p><div className="inline-add"><Input value={watch} onChange={e=>setWatch(e.target.value)} placeholder="שם או סימול, למשל TSLA"/><Button variant="secondary" onClick={()=>{if(!watch.trim())return;setProfile({...profile,assets:[...profile.assets,{kind:"watchlist",name:watch.trim(),symbol:watch.trim().toUpperCase().slice(0,12)}]});setWatch("")}}><Plus/>הוספה</Button></div></div><div className="section-card emphasis"><h3>תחומי עניין</h3><p>בחרו לפחות תחום אחד כדי להתאים גם את הסיפורים שמעבר לתיק.</p><div className="chips">{PRESETS.map(label=>{const active=interests.includes(label);return <button key={label} className={active?"selected":""} onClick={()=>setProfile({...profile,interests:active?profile.interests.filter(i=>i.label!==label):[...profile.interests,{label}]})}>{active&&<Check/>}{label}</button>})}</div><div className="inline-add"><Input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="חיפוש או הוספת תחום עניין"/><Button variant="secondary" onClick={()=>{if(!custom.trim())return;setProfile({...profile,interests:[...profile.interests,{label:custom.trim(),custom:true}]});setCustom("")}}><Plus/>הוספה</Button></div></div>{message&&<Notice>{message}</Notice>}<Button disabled={!profile.interests.length||busy} onClick={finish} className="primary-cta">{busy?<LoaderCircle className="spin"/>:<Sparkles/>} יצירת הבריף הראשון שלי</Button><Button variant="ghost" onClick={()=>router.push("/onboarding/confirm")}>חזרה</Button></>}
  </Card></main>;
}

function Generating({id}:{id:string}) {
  const router=useRouter(); const [brief,setBrief]=useState<BriefView|null>(null); const [reconnecting,setReconnecting]=useState(false);
  useEffect(()=>{let timer:number;let stopped=false;const poll=async()=>{try{const r=await fetch("/api/briefs/"+id,{cache:"no-store"});if(!r.ok)throw new Error("poll_failed");const b=await r.json() as BriefView;if(stopped)return;setReconnecting(false);setBrief(b);if(b.status==="completed"){router.replace("/briefs/"+id);return;}if(b.status==="failed")return;timer=window.setTimeout(poll,1200)}catch{if(!stopped){setReconnecting(true);timer=window.setTimeout(poll,2500)}}};void poll();return()=>{stopped=true;window.clearTimeout(timer)}},[id,router]);
  return <main className="center-screen generating"><Brand/><div className="orb"><Sparkles/></div><h1>מכינים את הבריף שלך</h1><p aria-live="polite">{reconnecting?"מתחברים מחדש…":brief?.stageLabel||"מתחילים…"}</p><Progress value={brief?.progress||5}/>{brief?.status==="failed"&&<><Notice>{brief.errorMessage}</Notice><Button onClick={()=>router.push("/today")}>חזרה להיום</Button></>}<small>נכסי התיק ותחומי העניין נשלחים ל־OpenAI רק לצורך יצירת הבריף.</small></main>;
}

function Today({profile,briefs}:{profile:Profile;briefs:BriefView[]}) {
  const latest=briefs[0]; const router=useRouter(); const [busy,setBusy]=useState(false);
  async function generate(){setBusy(true);const r=await fetch("/api/briefs",{method:"POST"});const data=await r.json() as {id:string};if(r.ok)router.push("/generate/"+data.id);else setBusy(false)}
  return <><div className="page-head"><div><span>{new Intl.DateTimeFormat("he-IL",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}</span><h1>בוקר טוב</h1></div><Button onClick={generate} disabled={busy||!profile.onboardingComplete}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>} בריף חדש</Button></div>{!latest?<Card className="empty-card"><Headphones/><h2>הבריף הראשון שלך מחכה</h2><p>הוסיפו תיק ותחומי עניין כדי ליצור בריף אישי ועדכני.</p><Button onClick={()=>router.push(profile.onboardingComplete?"/preferences":"/onboarding/portfolio")}>התחלה</Button></Card>:<div className="dashboard-grid"><section><Card className="hero-brief"><span className="pill">חדש</span><div className="brief-title"><div><h2>הבריף של היום</h2><p>{fmt(latest.durationMs)} · {latest.chapters.length} נושאים</p></div><Button size="icon" onClick={()=>router.push("/briefs/"+latest.id)} className="play"><Play fill="currentColor"/></Button></div><Wave/><div className="chapter-preview">{latest.chapters.slice(0,3).map((c,i)=><button onClick={()=>router.push("/briefs/"+latest.id)} key={c.id}><b>{i+1}</b><span>{c.title}</span><small>{fmt(c.durationMs)}</small></button>)}</div></Card><h3 className="section-heading">למה הנושאים האלה בבריף שלך?</h3><div className="reason-grid">{latest.chapters.filter(c=>c.reasonKind!=="general").slice(0,4).map(c=><Card key={c.id} className="reason"><span>{c.reasonKind==="portfolio"?"מהתיק":c.reasonKind==="watchlist"?"במעקב":"תחום עניין"}</span><b>{c.reasonLabel}</b><p>הסיפור נבחר בהתאם לפרופיל שלך.</p></Card>)}</div></section><aside><Card className="side-card"><div className="card-head"><h3>התיק שלך</h3><Link href="/portfolio">עריכת התיק</Link></div>{profile.assets.filter(a=>a.kind==="holding").map(a=><div className="holding" key={a.symbol}><span className="ticker">{a.symbol.slice(0,2)}</span><div><b>{a.symbol}</b><small>{a.name}</small></div></div>)}</Card><Card className="side-card"><h3>דופק השוק</h3><p>נתוני שוק מספריים יוצגו רק כאשר יש להם מקור מאומת.</p><div className="unavailable">לא זמין כרגע</div></Card><Link className="archive-link" href="/archive"><History/> לכל הבריפים הקודמים <ChevronLeft/></Link></aside></div>}</>;
}

function Player({id}:{id:string}) {
  const [brief,setBrief]=useState<BriefView|null>(null); const [active,setActive]=useState(0); const [playing,setPlaying]=useState(false); const audio=useRef<HTMLAudioElement>(null);
  useEffect(()=>{fetch("/api/briefs/"+id).then(async r=>r.ok?(await r.json() as BriefView):null).then(setBrief)},[id]); if(!brief)return <Loading/>; const chapter=brief.chapters[active];
  return <div className="player-page"><Link href="/today" className="back"><ArrowRight/> חזרה ללוח היום</Link><div className="player-layout"><Card className="player-card"><span className="pill">קול שנוצר באמצעות בינה מלאכותית</span><h1>{brief.title}</h1><p>{new Intl.DateTimeFormat("he-IL",{dateStyle:"long"}).format(new Date(brief.createdAt))} · {fmt(brief.durationMs)}</p>{chapter?.audioUrl&&<audio ref={audio} src={chapter.audioUrl} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>{if(active<brief.chapters.length-1)setActive(active+1);else setPlaying(false)}}/>}<div className="now"><span>פרק {active+1}</span><h2>{chapter?.title}</h2></div><Wave/><div className="player-controls" dir="ltr"><span>0:00</span><Button size="icon" onClick={()=>{if(audio.current){if(playing)audio.current.pause();else void audio.current.play()}}} className="play">{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</Button><span>{fmt(chapter?.durationMs)}</span></div><p className="script">{chapter?.script}</p></Card><aside><h3>פרקים</h3>{brief.chapters.map((c,i)=><button key={c.id} className={"chapter-item "+(i===active?"active":"")} onClick={()=>{setActive(i);setPlaying(false)}}><b>{i+1}</b><span>{c.title}</span><small dir="ltr">{fmt(c.durationMs)}</small></button>)}<h3>מקורות</h3><div className="sources">{brief.sources.map(s=><a href={s.url} target="_blank" rel="noopener noreferrer" key={s.id}><span>{s.publisher||s.title}</span><ExternalLink/></a>)}</div></aside></div></div>;
}

function Portfolio({profile,setProfile}:{profile:Profile;setProfile:(p:Profile)=>void}) {
  const [draft,setDraft]=useState(profile); const [name,setName]=useState(""); const holdings=draft.assets.filter(a=>a.kind==="holding");
  async function save(){const r=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});if(r.ok)setProfile(draft)}
  return <div className="narrow"><div className="page-head"><div><h1>התיק שלי</h1><p>עדכנו את האחזקות כדי לדייק את הבריף.</p></div></div><Notice>כמות ומחיר קנייה הם אופציונליים ולעולם לא יומצאו.</Notice>{holdings.map(a=><Card className="edit-asset" key={a.symbol}><div className="holding"><span className="ticker">{a.symbol.slice(0,2)}</span><div><b>{a.symbol}</b><small>{a.name}</small></div></div><Input placeholder="כמות (אופציונלי)" value={a.quantity||""} onChange={e=>setDraft({...draft,assets:draft.assets.map(x=>x===a?{...x,quantity:e.target.value}:x)})}/><Input placeholder="מחיר קנייה ממוצע" value={a.averageCost||""} onChange={e=>setDraft({...draft,assets:draft.assets.map(x=>x===a?{...x,averageCost:e.target.value}:x)})}/><Button variant="ghost" size="icon" aria-label="הסרה" onClick={()=>setDraft({...draft,assets:draft.assets.filter(x=>x!==a)})}><Trash2/></Button></Card>)}<div className="inline-add"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="שם או סימול של נכס"/><Button variant="secondary" onClick={()=>{if(name.trim()){setDraft({...draft,assets:[...draft.assets,{kind:"holding",name:name.trim(),symbol:name.trim().toUpperCase().slice(0,12)}]});setName("")}}}><Plus/>הוספת נכס</Button></div><Button onClick={save} className="primary-cta" disabled={!holdings.length}>שמירת שינויים</Button></div>;
}

function Preferences({profile,setProfile}:{profile:Profile;setProfile:(p:Profile)=>void}) {
  const [draft,setDraft]=useState(profile); const [custom,setCustom]=useState(""); const [watch,setWatch]=useState("");
  async function save(){const r=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});if(r.ok)setProfile(draft)}
  function addWatch(){if(!watch.trim())return;setDraft({...draft,assets:[...draft.assets,{kind:"watchlist",name:watch.trim(),symbol:watch.trim().toUpperCase().slice(0,12)}]});setWatch("")}
  function addCustom(){if(!custom.trim())return;setDraft({...draft,interests:[...draft.interests,{label:custom.trim(),custom:true}]});setCustom("")}
  return <div className="narrow">
    <div className="page-head"><div><h1>העדפות</h1><p>התאימו את הבריף למה שחשוב לכם.</p></div></div>
    <Card className="settings-card"><h3>אורך הבריף</h3><Select value={String(draft.targetMinutes)} onValueChange={v=>setDraft({...draft,targetMinutes:Number(v) as 5|7|10})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="5">כ־5 דקות</SelectItem><SelectItem value="7">כ־7 דקות</SelectItem><SelectItem value="10">כ־10 דקות</SelectItem></SelectContent></Select></Card>
    <Card className="settings-card"><h3>נכסים במעקב</h3><div className="chips">{draft.assets.filter(a=>a.kind==="watchlist").map(a=><button className="selected" key={a.symbol} onClick={()=>setDraft({...draft,assets:draft.assets.filter(x=>x!==a)})}>{a.symbol}<X/></button>)}</div><div className="inline-add"><Input value={watch} onChange={e=>setWatch(e.target.value)} placeholder="שם או סימול"/><Button variant="secondary" onClick={addWatch}><Plus/>הוספה</Button></div></Card>
    <Card className="settings-card emphasis"><h3>תחומי עניין</h3><div className="chips">{PRESETS.map(label=>{const active=draft.interests.some(i=>i.label===label);return <button key={label} className={active?"selected":""} onClick={()=>setDraft({...draft,interests:active?draft.interests.filter(i=>i.label!==label):[...draft.interests,{label}]})}>{active&&<Check/>}{label}</button>})}</div><div className="inline-add"><Input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="חיפוש או הוספת תחום עניין"/><Button variant="secondary" onClick={addCustom}><Plus/>הוספה</Button></div></Card>
    <Button onClick={save} className="primary-cta" disabled={!draft.interests.length}>שמירת שינויים</Button>
  </div>;
}

function ArchivePage({briefs}:{briefs:BriefView[]}) { return <div className="narrow"><div className="page-head"><div><h1>ארכיון הבריפים</h1><p>כל הבריפים נשמרים במחשב הזה בלבד.</p></div></div>{briefs.length?briefs.map(b=><Link href={"/briefs/"+b.id} key={b.id}><Card className="archive-row"><span className="ticker"><Headphones/></span><div><b>{b.title||"בריף אישי"}</b><small>{new Intl.DateTimeFormat("he-IL",{dateStyle:"long"}).format(new Date(b.createdAt))} · {fmt(b.durationMs)} · {b.chapters.length} פרקים</small></div><ChevronLeft/></Card></Link>):<Card className="empty-card"><History/><h2>עדיין אין בריפים בארכיון</h2></Card>}</div>; }
